### ISSUE TITLE
Next weapon key does not work when dual wielding

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#173]
### Version
current

### Environment
pc

### Port
GZdoom

### Description
Next and previous weapon keys do not work when dual wielding

**Comment by BLOODWOLF333** [comment]
That has been that way since brutalv21gold and there just isn't a better way to do this.  Have tried in the past adding all the dual weapons to KEYCONF and all the gamepad and cellphone users complained about it taking too long to then scroll through all the weapons to get to the one you want.  Can't take away the single PlasmaRifle and then Give the DualPlasmaRifle and vice versa because if you have the single and dual in inventory then there is no reason to even have the dual wield feature can just nextweapon and switch to duals so, there just isn't a better way to do this and am not going to waste my time with it.
`//Weapon Slots
weaponsection "Brutal_Doom"
//Last - first selected on key press
setslot 1 ClassicFist Melee_Attacks BrutalAxe ClassicSaw Chain_Saw DSWeap2 DSWeap
setslot 2 ClassicPistol BrutalPistol ClassicSMG BrutalSMG MP40 Revolver2 Revolver 
setslot 3 ClassicShotgun Shot_Gun ClassicSSG SSG AssaultShotgun
setslot 4 Rifle Machinegun ClassicChaingun MiniGun HitlersBuzzsaw
setslot 5 GrenadeLauncher ClassicRocketLauncher Rocket_Launcher
setslot 6 ClassicPlasmaRifle Plasma_Gun RailGun
setslot 7 NukeLauncher BFG10k VanillaBFG9000 BIG_FUCKING_GUN
setslot 8 Unmaker HellishMissileLauncher
setslot 9 FlameCannon Flamethrower2 
setslot 0 HandGrenades`
