### ISSUE TITLE
Melee combat

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#187]
### Version
current

### Description
Problems with melee combat:

1. Chainsaw is a gimmick weapon. It's OP vs single monster but useless if there is several tough monsters around.
Fix: replace it with axe. But axe needs to be buffed.

2. Axe is useless. Its DPS is too low when compared to fist combo.

3. Axe deals 5+35 damage. That 5 damage attack often misses.

4. Slide kick damage is OP vs monsters that are not knocked down. They get kicked about 20 times.
Fix: When player slide kicks a monster make player go thru the monster.

5. Berserk is weird. You pick it up and suddenly deal more than 5 times more melee damage.  It would be better if your melee damage was proportional to your health.  The more health you have the more damage you deal. This way you don't have to worry about finding berserk and melee combat is always fun.

**Comment by BLOODWOLF333** [comment]
1. No that is a weapon from vanilla and the rest of the community would throw a fit I have to go with the majority.

2. Honestly yeah it is and hopefull mark removes it and other redundant weapons in v22 but, i could just add the DamageFactor "Cut" back into monsters and that would buff it but, i think the chainsaw should be more powerful than the axe.  

3. I'll look into it.

4. There is no simple way i could do that and make it handle if the player released crouch/kick while inside a Mancubus and then cause some kind of collision error or one of the actors becoming telefragged.  Instead i can just make the attack stop once it hits another actor simple is better.

5. Because <500 hitpoint enemies take DamageFactor "Fatality", 5.0 from fatality damagetype attacks and >= 500 hitpoint actors take x2.5.  We don't need to over complicate stuff.  I removed those damage multiplications in earlier versions and ppl threw a fit about it so, theyre back in like how Brutalv21Gold was done and I'm not messing with it anymore.

**Comment by BLOODWOLF333** [comment]
two of the attacks were missing the check for GoFatality and GiveInventory("GoSpecial",1) I seen it happen a few times testing today on the Demon and can't break it now.
