### ISSUE TITLE
Menu text is cut off

### ISSUE THREAD

**Issue by mjrawesome** [BLOODWOLF333/Brutal-Doom-Community-Expansion#244]
### Version
State if you are using the stable or which development snapshot version.

- Stable v21.5.0

- Development v21.5.3

### Environment
State whether this occurs on a computer or mobile device.

- PC (W7x64); 1920x1200; 1920x1080

### Port
State which port this occurs on whether GZdoom, Zandronum, or another Doom port.

- GZdoom v4.5.0; Zandronum v3.0

### Description

I'm new to Doom modding, so sorry if this is a non-issue, but my main menu text is cut off in one place or another. With GZdoom it's cut off at the bottom (on both 1920x1200 and 1920x1080 display) and with Zandronum it's cut off on the right (on 1920x1200 display only) . Changing in-game resolution or aspect ratio doesn't appear to have any effect on this. The in-menu wallpaper is not cut off (although there are black sidebars with Zandronum). Everything else, including in-game graphics, looks and plays great. 

Is there anything I can do to fix this?

Also, I would suggest changing the font/color of the white words in the main menu as they don't seem to fit the rest. Just an idea.

Many thanks for creating and sharing this project!

**Comment by BLOODWOLF333** [comment]
Well, what is the aspect ratio of your monitor?  Because if your monitor is 1920x1080 (16:9) then that is the resolution you should use instead of 1200(16:10).  It does that for me as well if I pick a funky resolution that doesnt match my monitor.  But, all that render code is in the ports GZDoom or Zand and I cant fix that.

And in vanilla Doom or Doom2 the options menu has white text as well or are you talking about the white text around the "Brutal Doom" logo at the top of the screen in the main menu?

**Comment by mjrawesome** [comment]
Thanks for a reply. 

My gaming monitor is 1920x1200 (16:10) and I set the resolution as well as aspect ratio in the game accordingly, but the main menu text is always cut off either at the bottom or on the right. I tried this on a 1920x1080 (16:9) tv as well and the main menu text itself shows okay in Zandronum, but still cut off in GZdoom. 

[Perhaps this image will illustrate better what I mean](https://imgur.com/UHgmYRG). This is for GZdoom, while Zandronum has the end of "Brutal Doom Options" cut off.

As for the white text, I was referring to the words "Sergeant Mark IV's" and "Press F1 for in-game help.", which can be seen in the picture linked above. Also, perhaps it would be a good idea to apply the textures used for the word "DOOM" to the word "BRUTAL"? At the moment, all those lines/words above "New Game" in the main menu do not seem to have any consistent style... they look rather random. Just my opinion.

**Comment by BLOODWOLF333** [comment]
Options>Set Video Mode> and set the scale to 1.0, fullscreen yes, select a resolution preset that matches your aspect ratio and then apply changes (fullscreen).  But, I'm not really sure I cant duplicate your concern so, could just get on the ZDoom discord and ask them because the GZDoom devs feel the need to change/fix things that are not broken.  All I use Zandronum it's simple and it works.

And the white text on the Brutal Doom logo that is all a single image and is Mark's artwork and I'm not an artist so I don't want to mess with that.  No one else is bothered by it.

**Comment by BLOODWOLF333** [comment]
Was told on the Brutal Doom Discord that in the latest GZDoom options there should be a misc options and you just need to turn off menu scaling if all else fails

**Comment by mjrawesome** [comment]
Now that I had a closer look at this, it's obvious that you reused original main menu fonts for the additional "Brutal Doom Options" and "Credits" entries, which made the menu list too wide and too long... You can play with resolutions, aspect ratios and scaling all day, but it isn't going to do squat. 

Apparently, I have the soul of an artist, because I fixed the issue and made the menu look [a few orders of magnitude better](https://imgur.com/1TPN6ZM) in about 30s by just using Paint. Sadly, part of the fix involved removing the "Credits" entry... LMFAO.

**Comment by Skrell** [comment]
> 
> 
> Now that I had a closer look at this, it's obvious that you reused original main menu fonts for the additional "Brutal Doom Options" and "Credits" entries, which made the menu list too wide and too long... You can play with resolutions, aspect ratios and scaling all day, but it isn't going to do squat.
> 
> Apparently, I have the soul of an artist, because I fixed the issue and made the menu look [a few orders of magnitude better](https://imgur.com/1TPN6ZM) in about 30s by just using Paint. Sadly, part of the fix involved removing the "Credits" entry... LMFAO.

Can you please share how you fixed the font?  I'm so sick of the menu screen looking horrible.
