### ISSUE TITLE
Inadequate Death Animation Variety

### ISSUE THREAD

**Issue by EliasHeydrich** [BLOODWOLF333/Brutal-Doom-Community-Expansion#262]
I am using **brutalv21.6.0** with an Ultimate Doom WAD on Zandronum 3.0. Since switching to the community edition, I have noticed that "monster death animation variety" was different.

I ran the following test now, launching the game as follows:
`zandronum.exe -iwad DOOM.WAD -file brutalv21.6.0.pk3 IDKFAv2.wad`
and selecting a rifle start on _Hurt me Plenty_.

When running to the end of the level and gunning down every Zombieman I see with that rifle, they all die with the exact same classic way, falling backwards from a chest hit. I gunned down further Zombieman in E1M2 afterwards with similar results.
I ran the test again, trying to hit critical zones this time, like the head. I managed to trigger one headshot animation death only (which might indicate I am a bad shot **or** be problematic game behavior).

Vanilla Brutal Doom v21, as far as I remember, does not work like this. I am going to repeat the same testing process later to verify/falsify this death animation behavior (but even if this is not a bug in the CE then something must be done here, I am certain this was better in the past).

Note that I am seeing some script warnings on my Zandronum that look problematic to me, **but I am not firm enough in Doom Modding to determine if these are safe to ignore**.

**Comment by BLOODWOLF333** [comment]
If your seeing the script warnings about the DoomerFace those can be ignored since the DoomPlayer has nothing defined for it's face that way the script can change it to male or female (only way we have of doing this as far as I know).  Shouldn't be any other start-up errors with just my mod loaded in-place of the original brutalv21.pk3.

The rifle fires bullets with the "HitPuff" puff on impact which is the same between v21Gold and v21.6.0.
HitPuff does damagetype "Bullet" which is the same between both versions.
Zombieman and Shotgunguy's don't have a Death.Bullet: state defined so they go to the normal Death: state.
Zombiemen Death state has a 32/256% chance to jump to Death.Arm otherwise goes to Death.Minorleg: and is the same between the versions.
Shotgunguy Death state has a 96/256% chance to jump to Death.Arm else has a 48/256% chance to jump to Death.Leg otherwise goes to Death.Minor: and I didn't change those or the probabilities between the version either.  So I don't know man?

**Comment by EliasHeydrich** [comment]
I have tested this with BDv20 and BCv21 and **you are correct**. Seems I was mistaken or did just not use the rifle that often before.

Consider this to be a low-prio feature request for more death-states instead, which may or may not be out of scope for this expansion.

**Comment by BLOODWOLF333** [comment]
Ok, yeah I suck at monster sprites and drawing on the computer in general but, if Doxx or someone ends up making new ones down the road I can add them later.
