### ISSUE TITLE
[Suggestion] Move some stuff to Level Enhancement System

### ISSUE THREAD

**Issue by neonvortex** [BLOODWOLF333/Brutal-Doom-Community-Expansion#267]
There are a handful of textures that BD unconditionally replaces, such as the grass textures and a step texture. These should probably be moved into the level enhancement system, if possible, for compatibility with mods that replace those textures with something different; I don't know if Extermination Day will look correct though. The new bosses should also probably be moved to level enhancements as well, if players want to fight the normal enemies on those levels.

**Comment by BLOODWOLF333** [comment]
Yeah I can do this.

**Comment by BLOODWOLF333** [comment]
Can you give me specifics?  Because some of those textures like the steps are a patch in brutal doom and others are being told to be replaces in the CVARS file:
`SCRIPT "BDInitiate" OPEN
{
	if (GetCvar("bd_disablemapenhancements") == 0)
	{
		ReplaceTextures ("DSAND1", "SANDS1");
		ReplaceTextures ("DSAND3", "SANDS1");
		ReplaceTextures ("DSAND4", "SANDS1");
		ReplaceTextures ("DSAND5", "SANDS1");
		ReplaceTextures ("ETEX34", "SANDS1");
		ReplaceTextures ("WALL81", "SANDS1");
		ReplaceTextures ("ECEIL13", "SANDS1");
		ReplaceTextures ("ECEIL15", "SANDS1");
		ReplaceTextures ("GROUND20", "DESERT01");
		ReplaceTextures ("SLUDGE01", "SLIME08");
		ReplaceTextures ("LFALL1", "LFALL01");
		ReplaceTextures ("LAVA1", "LAVAFL");
		ReplaceTextures ("LAVA2", "LAVAFL");
		ReplaceTextures ("LAVA3", "LAVAFL");
		ReplaceTextures ("LAVA4", "LAVAFL");
		ReplaceTextures ("LAVA01", "LAVAFL");
		ReplaceTextures ("LAVA02", "LAVAFL");
		ReplaceTextures ("LAVA03", "LAVAFL");
		ReplaceTextures ("LAVA04", "LAVAFL");
		ReplaceTextures ("LAVFALL1", "LFALL01");//Sunlust Lava
		ReplaceTextures ("SLMFALL1", "CRFAL01");//CRAPFALLS
		ReplaceTextures ("SLMFALL2", "CRFAL01");//CRAPFALLS
		ReplaceTextures ("SLMFALL3", "CRFAL01");//CRAPFALLS
		ReplaceTextures("FLOOR5_3", "METAL52");
		ReplaceTextures("FLOOR5_2", "METAL52");
		ReplaceTextures("FLAT5", "METAL53");
		ReplaceTextures("FLOOR0_1", "METAL54");
		ReplaceTextures("FLOOR0_3", "METAL55");
		ReplaceTextures("FLOOR3_3", "METAL56");
		ReplaceTextures("TLITE6_5", "LITGEN7B");
		ReplaceTextures("TLITE6_6", "LITGEN9C");
		ReplaceTextures("FLAT2", "FLAT2B");
		ReplaceTextures("GRNLITE1", "GRNLIT1B");
	}
}`
But I did get rid of the lines replacing BLODGR1 and DBRAIN1 with lava textures which didnt make sense to me.

**Comment by neonvortex** [comment]
The textures it always replaces are GRASS1 and the liquid textures (BLOOD, FWATER, LAVA, NUKAGE, and SLIME). The step patch is I think the only place where BD just replaces a texture instead of swapping it out.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/105912340-f3159600-5ff0-11eb-8aaf-c8cfe238e683.png)
Yeah the whole Textures folder in brutal doom is going to act like a patch when it gets loaded after the IWAD or a map WAD.....I don't see a simple way of doing this without tons of tedious renaming of textures and then a big script to replace vanilla textures with the new ones if mapenhancements are on.  And some of them are from like Epic 2 and other mappacks that Mark made map specific decoration spawns for and have to have that map-specific texture name in the mod for when you do play it or else you get start-up errors.  And that placeholder texture then acts like a patch.

**Comment by BLOODWOLF333** [comment]
So, I've been tinkering with this and I can make it not replace the ground flats/textures unless the mapenhancement cvar is true but, for liquids your still going to get Brutal Doom's splashes because the Terrain lumps overwrite each other and the weapons (like the rocketlauncher) fire a splash maker that checks the floor texture then spawns that liquid's splash effects.  So, like in Stardate20x6 the nukage is colored purple but, with BD loaded your still going to get green splashes when shooting the water.  I not sure this is even worth it anymore.
