### ISSUE TITLE
Tanks in Eday and Hell on earth not working.

### ISSUE THREAD

**Issue by Matty4818** [BLOODWOLF333/Brutal-Doom-Community-Expansion#268]
I am running Brutal Doom V21 through GZDOOM 4.2.1 with the Extermination Day Pre Beta Mod Map Pack. Last week I was playing on the weapons testing map and the tanks were moving around fine, along with the mobile turrets. Today I load up the same thing again and now the tanks won’t work in the campaign or the weapons testing map. I tried the Hell On Earth Map Pack as well and the same thing occurs.  What could be the reason(s)? Any help would be great! Thank you.

**Comment by BLOODWOLF333** [comment]
Your going to have to list the exact file names and load order your using but, that Hell On Earth Starter Pack in ancient from 2015.  This is the latest version of Extermination Day (in the Brutal Doom Discord):
edaytest001.pk3
https://www.mediafire.com/file/90vtv2gno6ynk5x/EdayTest001.zip/file

And edaymusictestdec09.wad is the latest music addon for it:
https://allfearthesentinel.net/zandronum/wads.php?&name=eday&md5=&user=&tags=

Retest with those and my brutalv21.7.0.pk3 file instead of the old brutalv21.pk3 cause I'm not able to duplicate that concern right now.

1.  Doom2.wad
2. edaytest001.pk3
3. brutalv21.7.0.pk3
4. edaymusictestdec09.wad

**Comment by Matty4818** [comment]
Where can I get your brutalv21 7.0.pk3? Can you send me a link?

**Comment by BLOODWOLF333** [comment]
Click the [Code] tab at the top left of the screen and then the Releases button on the right hand side of the screen
https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/releases/tag/v21.7.0

Also on moddb
https://www.moddb.com/mods/brutal-doom/downloads/brutal-doom-v2170-expansion-stable

**Comment by Matty4818** [comment]
Thank you!

**Comment by BLOODWOLF333** [comment]
Is this issue resolved?

**Comment by Matty4818** [comment]
Yes everything works now that I downloaded the new version of extermination day.
