### ISSUE TITLE
When throw axe at enemies gets carbonized

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#299]
### Version
-master

### Environment
PC

### Port
LZDoom  v3.87c
When throw axe at enemies gets carbonized having plasma gun hitting in the head.

https://user-images.githubusercontent.com/76774186/114762391-61edca00-9d6a-11eb-8b1d-892a9b644bbe.mp4

**Comment by BLOODWOLF333** [comment]
That is because you did the cheat code IDFA or IDKFA which also is giving you all the inventory tokens like "HasPlasmaWeapon" which will cause the zombies to jump to the plasma death state if they die from head damage and the target has that token in their inventory.  If you just `summon brutalaxe` in the console and retest it they will die normally after being hit in the head with a thrown axe.

**Comment by BLOODWOLF333** [comment]
After thinking more about it, this annoys me and I can "fix" this.
