### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by Real-Gecko** [BLOODWOLF333/Brutal-Doom-Community-Expansion#306]
Is there a way to profile ACS or ZScript to pinpoint locations which cause performance issues?
For example EDAY05 is barely playable due to performance drops on GZDoom 4 with BD21(any version actually, from RC1 maybe). Funny thing is that there's no performance issues with Zandronum. There's some info about difference in rendering engine for both, but with GTX1070 I think ~0.5 FPS is not an option on any engine. So I'd love to pinpoint the problematic part and maybe help fix it.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/118414527-b38bbc00-b66a-11eb-8d1a-afcc60b90098.png)
idk what render option do you have selected?  I hate GZDoom I only play zand cause Graff likes to "fix" things that were not broken and makes it retarded to maintain compatibility with brutal doom.

**Comment by Real-Gecko** [comment]
Well, it's actually absolutely not important which renderer I choose, it's same shit with OpenGL, Vulkan or software modes. That's why I presume the problem is not graphics subsystem, but some other stuff. So, do you propose to stay with Zandro and leave GZ behind?

**Comment by BLOODWOLF333** [comment]
The majority of the community plays on GZDoom, I play online all the time and dont care about all of GZDoom's fancy stuff so, I dont miss it.  Mark says v22 will run way better and I do know that the blood decals + the flashlight causes large frame drops as well as the barrel explosions and all the gore spawns when many monsters are being killed at the same time like from a bFG blast.  So, waiting to see what Mark comes up with.

**Comment by vsonnier** [comment]
For GZDoom here is a few commands to type on console to profile code:  
-  `stat think` to have an idea of how many actors (things, thinkers) actually running. Repeat command to disable. Type `stat` to know what options are available. 
-  `profilethinkers +t` : will give you, per type of actor how many times is spent. Others options are availablea as well, type `profilethinkers` to show.

**Comment by Real-Gecko** [comment]
Thanks for the info. Also FPS drops are "floating", it's like very smooth for ~4-5 seconds, and then it goes below 1 for same ~4-5 seconds. And it depends on level, some levels are OK, some have this issue, that's why I want to profile it. Without BD the maps are totally fine, so I guess it's not a map issue.

**Comment by vsonnier** [comment]
Any logs of the above commands are interesting. 

For instance, I've already fixed bugs in Brutal Doom Black Edition long ago, inherited from BD where an insane number of Headshot actors were spawned (`HeadTargetXXX`) because of clearly buggy BD code. If it is the same thing, it will be easy to fix by @BLOODWOLF333 if he wants to. 

Now why Zondro is less sensitive to this may be because it supports less features in actors, whch cost way less to spawn, I don't know.

**Comment by BLOODWOLF333** [comment]
> Any logs of the above commands are interesting.
> 
> For instance, I've already fixed bugs in Brutal Doom Black Edition long ago, inherited from BD where an insane number of Headshot actors were spawned (`HeadTargetXXX`) because of clearly buggy BD code. If it is the same thing, it will be easy to fix by @BLOODWOLF333 if he wants to.
> 
> Now why Zondro is less sensitive to this may be because it supports less features in actors, whch cost way less to spawn, I don't know.
> 
> I'll test EDAY05 later.

So you removed the head and legshot actors entirely looking at your Brootal Doomb repo?  Nobody would play my mod if I did that.  Probably would run better though.

**Comment by Real-Gecko** [comment]
So I've executed `profilethinkers +t` and aggregated results [into spreadsheet](https://docs.google.com/spreadsheets/d/1F8d93yhlOBTOAaJDgIwgS4L-VYsPwRv9yr9eVgoF-KA/edit?usp=sharing). Page 1 contains results when FPS was good, second during FPS drop, don't know if it makes any difference. However in both cases I see the weapon spawners take the most time with `RifleSpawner` being most demanding one.

**Comment by vsonnier** [comment]
@BLOODWOLF333 

> So you removed the head and legshot actors entirely looking at your Brootal Doomb repo? Nobody would play my mod if I did that. Probably would run better though.

I agree completly, BD is nothing without headshots and the related animations. Brootal Doomb is just a clone of https://github.com/MekBoss/Brootal-Doomb to study how the BD Zscript convertion was about, this is not my work. Brootal-Doomb didn't remove the headshots, but used a 100 % ZScript solution using `DamageMobj` overrides for monsters, which is a way to catch and transform the damage applied on them.

I didn't copy that mechanism for Brutal Doom Black Edition (https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-v20b-black-edition) though. BE is a mix of BD v20b code with a ever increasing part of Zscript. 

In that code I simply found excessive usage of `HeadTargetXXX` with pattern like this:

```asm
Stand:
 	TNT1 A 0 A_CheckSight("Stand2")
         // original code:	TNT1 A 0 A_SpawnItem("HeadshotTarget100", 0, 56,0)
	TNT1 A 0 A_SpawnItem("HeadshotTarget20", 0, 56,0) // fixed
 	BOS2 BB 10 A_Look
 	Loop
```
which literaly spawned 1 `HeadshotTarget` with a duration of 100 ticks... every 20 Ticks, which result an insane amount of spawned `HeadTarget` actors that lived way longer than the state they were supposed to cover. 

That's the kind of easy fix I was talking about.

But this is clearly not the culprit here.

@Real-Gecko  Thanks for your test.
**3.961786** | 0.330149 | 12 | ChaingunSpawner
-- | -- | -- | --
**31.613** | 1.317208 | 24 | RifleSpawner
**9.451973** | 0.32593 | 29 | ShotgunSpawner

I see similar offenders, and they are clearly causing the slowdown you observe. 

@BLOODWOLF333  in `WeaponSpawners.txt` they have a common pattern for them Spawners for which I suggest a fix :

```asm
Spawn:
	RIFL A 0
	TNT1 A 1
	TNT1 A 0 A_ChangeFlag("THRUACTORS", 0)
	TNT1 A 0
Stay:
	TNT1 A 0
	TNT1 A 0 A_SpawnItem("FakeSMGSprite")
	TNT1 A 0 A_SpawnItem("FakeRifleSprite")
	TNT1 A 1
	Loop // <== Why not using Stop here, instead of looping and continously spawn  FakeXXX sprites ????
```

**Comment by BLOODWOLF333** [comment]
I could make the fake sprites loop instead of the spawner but those fake sprites are for Purist player class compatibility who can't use the rifle so the fake SMG sprite which is only visible to Purist class, is seen and is the weapon they will pick up.  Same with the shotgun and chaingun spawners so that the purist player sees the classic weapon sprites. Idk if a looping fake sprite would be better though but can try it.

**Comment by BLOODWOLF333** [comment]
Actually I cant do that or the fake sprites wont disappear.  I can just make the Stay: state last longer so its not eating up so many resources I guess.

**Comment by vsonnier** [comment]
@BLOODWOLF333 Interesting, thanks for the explanation.

**Comment by Real-Gecko** [comment]
Hell yeah! Now we're talking! EDAY05 is now fully playable even on GZ with c522ac6.
The only thinker that's very time consuming is `ShotgunSpawnerDroped`, but I guess it's due to actual drop animation. [Here's aggregation again](https://docs.google.com/spreadsheets/d/1e5SFR2ScLPI4c4ULSUGgBff1EnKwrTEjXr9S3yoh2eQ/edit?usp=sharing).
Thanks for help and fix.

**Comment by BLOODWOLF333** [comment]
Oh shit, that actually worked?  The real achievement will be getting Sunlust Map30 to not freeze at the start of the level with brutal doom.

**Comment by Real-Gecko** [comment]
Let's dive deeper in this rabbit hole: [HELLBOUND MAP29](https://docs.google.com/spreadsheets/d/1zU7XDig6_wR0pUZVE0r5eNrgSkM4plEuBKgQDcJ9hek/edit?usp=sharing). I understand that this map is pretty damn heavy by itself, but maybe we can do something about it :D

**Comment by BLOODWOLF333** [comment]
Do the aggregation again and I can address the worse actors but, I got a lot of other things I want to fix today as well.

**Comment by Real-Gecko** [comment]
@BLOODWOLF333 it's not urgent so take your time, I'll see how Sunlust works in GZ, I bet if performance will be acceptable there in Zandro it'll be hypersonic :D

**Comment by vsonnier** [comment]
For Hellbound map29 the heaviest actors are the monsters themselves here, there are many, and none of them seem to stand out (an unusual long time spent per monster instance) . Ex 4.8ms is spent for Imps, but there are 679 of them :) So good luck to optimized that.

On the other hand, considering their small amount, `LifeSphere`, `GasSpawner`, `Fireball_`, `HeavyArmor` and even `EnergySphere` are probably doing something funky. 
And what about those `Brutal_xxxBlood` too which probably will multiply with the gore while playing the level ?

Well you got the idea. 

If  `profilethinkers` does what I think it does, it is measuring the time spent "thinking" for __each tick__ i.e. 1/35 s, so few ms in that list quickly impacts the game.

And now I'm curious and will test Sunlust Map30 as well :)

**Comment by Real-Gecko** [comment]
Hey guys! [Here is profiling results](https://docs.google.com/spreadsheets/d/1IaVw2yszHQe6_2dXMuB03Rrmt7Zbtv9hfDJMunbcwYI/edit?usp=sharing) for Sunlust MAP30 with 4fadc05. There's a lot of stuff going there and some things that're not important for gameplay (according to actor class name) executed thousands of times:

<google-sheets-html-origin>
Calls | Actor class
-- | --
6224 | InternalDynamicLight
4823 | ExplosionSmokeHDLarge
4118 | RedFlareSmall

</google-sheets-html-origin>

Maybe some of this stuff may be disabled via options or something like this? Because we definitely can live without `TinyBurningPiece` which is called ~1500 times and takes 10 seconds or without `SmallFireFocus24` which is called 1270 and takes **252.157355 seconds**

**Comment by Real-Gecko** [comment]
Fun fact if `freeze` command is issued in console, the game freezes and runs smoothly (of course, everything is frozen :D), I issued `profilethinkers` again in this mode and [added the results to profile sheet](https://docs.google.com/spreadsheets/d/1IaVw2yszHQe6_2dXMuB03Rrmt7Zbtv9hfDJMunbcwYI/edit?usp=sharing) as page 2. The weird thing is it looks like the list of thinkers is changed.

**Comment by vsonnier** [comment]
@Real-Gecko I think all those thinkers you see are the aftermath effects of the shitton of `ExplosiveBarrel` that somehow go off just after starting the level. 

Try to run `profilethinkers +t` just after 'map map30' on the same console, you should see 2000+ `EsplosiveBarrel` listed.

**Comment by BLOODWOLF333** [comment]
So in your list you can insert another column and divide the load time by the number of actors to pinpoint which ones actually are taking the longest time to load but, Map30 of sunlust like vsonnier pointed out has over 2,000 barrels exploding at the start in monster closest to then teleport the corpses into the map for archviles to raise later on.  So, I cant fix there being x2000 spawns of actors from the barrel when it explodes but things like making the power-ups less intensive with all the flare spawns I can take care of.

**Comment by vsonnier** [comment]
> exploding at the start in monster closets to then teleport the corpses into the map for archviles to raise later on. 
So, I cant fix there being x2000 spawns of actors from the barrel when it explodes 

We may in fact. I tested on BD and Black Edition and it was making a great difference, something like:

```asm
Death:
		TNT1 A 0 A_CheckSight("DeathTooFar")
                BEXP BCD 4 BRIGHT
		TNT1 A 0 A_Explode(200,200)
                ... etc.
	       Stop
	
DeathTooFar:
            BEXP BCD 4 BRIGHT
	   TNT1 A 0 A_Explode(200,200)
                ... etc.
             Stop
```

With `DeathTooFar` being the similar as `Death`, but stripped off its more demanding and transient effects like: particles, shrapnel, shockwave, buning piece, `ExplosionFlareSpawner`, `ExplosionSplashSpawner`, while keeping the most "visible" ones like smoke, quake, sound.

Something like:

```asm
DeathTooFar:
        BEXP BCD 4 BRIGHT
		TNT1 A 0 A_Explode(200,200)
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)//floor decal
	    TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)//ceil decal
		TNT1 A 0 A_ScreamandUnblock
		TNT1 A 1 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		TNT1 A 1 Radius_Quake (2, 24, 0, 15, 0)
		TNT1 A 0 A_CustomMissile ("HighExplosiveFlames", random (10, 20), 0, random (0, 360), 2, random (10, 90))
		TNT1 A 1 A_PlaySound("FAREXPL", 3)
		TNT1 A 320 BRIGHT A_BarrelDestroy
		TNT1 A 4 A_Respawn
		Stop	
```

BTW I agree about your change:  https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/commit/ff06279305b3f9e9819326a1f9a0e73bfb4006dd The "not visible" Stand version for monsters was quasi-identical to the "visible" ones, wasting time to useless `A_CheckSight`.

**Comment by BLOODWOLF333** [comment]
yeah I see why he had the second stand2 state in some monsters that didnt spawn headshot actors or any effects like for lost souls but, on the Zandronum discord their devs have explained to me previously that A_CheckSight() is a very inefficient and resource intensive function to call every few tics in a looping state so, was hoping removing those would make a difference.

**Comment by BLOODWOLF333** [comment]
And the barrel death yeah I will try that DeathHidden idea and will only keep any damaging actor spawns and see if that allows Ma30 to function smoothly in Sunlust but, it may also just be all the ridiculous amounts of gore that are being spawned by the monsters that are getting blown up by the barrels ontop of that as well but, we will see tonight.

**Comment by vsonnier** [comment]
Yes `A_CheckSight` is expansive, but it could be replaced by a very cheap (by comparison) `A_CheckRange(2000, "HiddenVersion")` were only the distance to Player is accounted for: if some actor is far enough from the Player we can skip some effects the Player would not see anyway because of the distance. 
I've used it in Black Edition, in order to skip small effects like for example magazines and castings ejections by monsters if they are far enough. 
Something between 1000 - 2000 units seemed to fit all cases.  In Sunlust case I tested `A_CheckSight` vs. `A_CheckRange` didn't seem to be different performance-wise at the begining of the level for BD / BE. (in GZDoom)

**Comment by vsonnier** [comment]
Speaking of expansive `A_CheckSight`, on GZDoom there is a `stat sight` command just to profile such calls.

**Comment by vsonnier** [comment]
Another rambling of mine : upon testing, I think it is wise to stick for `A_CheckSight` : there is plenty of cases where you wand to snipe an ExplosiveBarrel from afar with the Rifle or other, and see the destruction it causes with all the pretty effects. 
You certainly don't want to see castrated SFX because too far. 
So `A_CheckSight` it is for the ExplosiveBarrel.

**Comment by Real-Gecko** [comment]
Hey guys! Tried 8025b42 with Zandro and it's pretty awesome, even my personal troublemaker Going Down MAP28 is pretty damn smooth, Sunlust MAP30 has a huge freeze in the beginning and then is smooth too.  Did not try wit GZ though.

**Comment by BLOODWOLF333** [comment]
I cant fix the freeze/FPS drop on Sunlust Map30 thats just some ridiculous hacks the map author did so, if your satisfied close the issue please.

**Comment by Real-Gecko** [comment]
I'm not playing Sunlust, but anyway thanks for your work, as things are much better now.
