### ISSUE TITLE
Slumped dead bodies never show slumped dead bodies no head

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#307]
### Version
Brutal-Doom-Community-Expansion-master

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
Slumped dead bodies (imp, zombieman, shotgunguy, chaingunner) never show slumped dead bodies no head sprite when shoot the head.

https://user-images.githubusercontent.com/76774186/118851128-22bb1780-b8da-11eb-8c02-b11f75e59055.mp4

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20210519_160229](https://user-images.githubusercontent.com/16950832/118884337-ee386300-b8bb-11eb-91fc-063e54b6b640.png)
I cant duplicate that with the current state of 21.10.0 or with 21.9.0.  What else are you loading with brutal doom expansion because I made a new headshot actor for slumped bodies so that the friendly marines would quit targeting them?

**Comment by Nic-Usor** [comment]
At slumped dead imp show slumped dead no head when shoot the head, but some possessed monsters (zombieman, shotgunguy and chaingunner) never show. I don't idea what a bug caused.
![Screenshot_Doom_20210520_003710](https://user-images.githubusercontent.com/76774186/118888065-d684cd00-b903-11eb-9062-b362e150b17c.png)

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20210519_164727](https://user-images.githubusercontent.com/16950832/118888901-eb407100-b8c1-11eb-8895-5573d1e0b4d8.png)
nope theyre working correctly.  Your going to have to start using Google translate dude I can hardly understand you.

**Comment by Nic-Usor** [comment]
Trying to use command "summon" zombieman, shotgunguy, chaingunguy. What is the result?

**Comment by BLOODWOLF333** [comment]
the headshot actors were spawning inside or behind the wall where the player couldnt shoot them.
