### ISSUE TITLE
Slumped dead bodies never falls on the floor

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#314]
### Version
brutalv21.10.0.pk3

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
Slumped dead bodies (imp, zombieman, shotgunguy, chaingunner) never falls on the floor.

https://user-images.githubusercontent.com/76774186/119980408-e5831380-bfc4-11eb-846b-19f3a5915464.mp4

**Comment by BLOODWOLF333** [comment]
Dude this is an old 1993 game engine that is an extremely edgecase occurance.  There is no way I can make it check if it's against a door or something weird like that.  It uses A_Recoil for the initial thrust backwards, waits 6 tics and if it's still moving then goes to the lay down state otherwise it slumps against a wall.  I cant add another A_Recoil in the static looped state in the case of a door then opening behind it because it would start to slide against the wall and immediately go to the lay down state.  There is no way to "fix" this the game engine is limited.
