### ISSUE TITLE
Monsters that have colored blood spawn red blood some explosives weapons, heavy machinegun and friendly marine

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#353]
### Version
v21.11.1 Stable-Patched

### Environment
PC

### Port
Zandronum and LZDoom

### Description
Monsters that have colored blood spawn red blood when you go to the blood option and choose "Lots", "Extreme" and "Comical".

For example:
Grenade Launcher
https://user-images.githubusercontent.com/76774186/142482285-a3031b45-f66e-43ce-8a39-3da9018e328d.mp4

Machinegun with underbarrel grenade launcher
https://user-images.githubusercontent.com/76774186/142482424-69e0c30e-2e9a-4a03-a7a8-e544debd5590.mp4

Heavy machinegun
https://user-images.githubusercontent.com/76774186/142482678-439aed6e-8d02-4510-adae-aa03f8b541ca.mp4

And friendly marine
https://user-images.githubusercontent.com/76774186/142482814-2e743a4f-6c81-4663-95f2-6f167ce695e4.mp4

**Comment by BLOODWOLF333** [comment]
So this is another engine limitation.  There is only a single Bloodsplatter actor from vanilla Doom and its red, no way to define a blue and green bloodsplatter actor for use with the colored-blood demons and every explosive projectile like the marine tracers, explosives, and heavy MG projectiles had +BLOODSPLATTER so they would spawn the bloodsplatter actors when hitting a target but, that hack doesnt work with the goofy increased blood feature since its only red.
