### ISSUE TITLE
Revert The Rifle

### ISSUE THREAD

**Issue by ColonelSandersLite** [BLOODWOLF333/Brutal-Doom-Community-Expansion#362]
It's hard for me to adequately express just how bad the new rifle is in practice.

I know.  ACOGS are cool.

That being said, putting an ACOG on the rifle turns your starting weapon, or one of the first couple of weapons you're likely to get, into a weapon which is only really good at long ranges.

Further, the level of zoom is, quite frankly, excessive.  It's more than the rocket launcher gets and that's blatantly not meant to be a close quarters weapon at all.  Strafing at like 60mph with a 2x or 3x or whatever zoom in an enclosed room is nausea inducing.  I say that as a guy that has been gaming for a pretty long time and is very resistant to that sort of thing.

Additionally, without making the scope take up the whole screen as it does with the rocket launcher/rail gun, the zoom is very disorienting.

So you have turned a perfectly fine starting multi-purpose gun into something that's wildly impractical in a close quarters fight but great for plinking down zombies from 300 yards.  This is doom.  We very rarely need such a weapon.  We need such a weapon at the start of a map even less.

Maybe fixing the zoom mechanics would make the gun usable but seriously, I just want my irons back.  Maybe a red dot.  Those are pretty cool too.

**Comment by BLOODWOLF333** [comment]
I've been playing through all the cacoward winners and some of these megawds have huge maps and I have wanted an ACOG/scope for years since I started playing.  Vanilla Doom and Doom2 yeah its not really needed but, there have been several wads where I have wanted/needed it and didnt have the ammo for the railgun and the rocketlauncher projectile was too slow.  Up close just dual wield it or use the machinegun or minigun which are better close-range weapons.  This way the rifle doesnt become completely obsolete.  And the old Aim Down the Sights sprites I dont think matched the carrying handle of the weapon specially when you see it from the side while dual wielding (neither do the SMG ADS sprites and the SMG's pickup sprite sucks too which I will try to change later).

I actually use the rifle now that it has a useful increased zoom and hitscan attack like a sniper when I dont want to waste cell ammo with the railgun because there are 8 cyberdemons on this map and the target is moving so the rocketlauncher would miss and waste ammo.

**Comment by ColonelSandersLite** [comment]
Up close, yeah, you can use the minigun/mg *if* you have them and *if* you have the ammo to run them.  Dual wielding doesn't solve the inability to aim.

And that's sort of my point - I don't have a problem with a sniper or DMR sort of rifle being in the game.  I really don't.  It's a big problem that it's the starting gun.

The rifle was good when you where low on shells and engaging trash, didn't have the shotgun yet, or needed to engage a target at more of a mid range.  It lost two of those qualities.  That wouldn't be such a big deal if it wasn't an early weapon.


If you really must have a DMR sort of thing, TBH, I would drop the SMG and and replace SMG sergeants with DMR sergeants.  Or alternatively, drop the MG for a DMR.  It's honestly pretty redundant.  Or just add a DMR.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20211207_173002](https://user-images.githubusercontent.com/16950832/145122037-7740d982-f433-481f-aa07-bd93d0ab9110.png)
Im not a sprite artist, this is me trying to make the SMG pickup sprite better I dont know how to recreate Doom's pixel art style in Gimp.  The old BD Rifle ADS sprites did not match the weapon.  Like when you dual wielded it and seen the carrying handles but then when aiming down the sights it didnt match and looked bad so, I wanted it to change.  
![RIFZC0](https://user-images.githubusercontent.com/16950832/145122266-f77530cc-f7a8-4ec2-b6f8-6ca13609142f.png)
![RISPA0](https://user-images.githubusercontent.com/16950832/145122272-df771db1-3c0e-48e4-bd1c-6d96ff2b7b65.png)
That stuff ^^^ has bothered me for years.  I will try to frakensprite the machinegun's M203 grenade launcher onto the new rifle and manipulate its sprite to use the iron sights and call it a "battle rifle" which will be the starting weapon for rifle start and tactical player classes (why dont you just use the shotgun start player class?  thats all I ever play as) and have it replace the machinegun entirely because that weapon doesn't really have a place.  but, im not giving up my ACOG sniper rifle I use it and put a couple of days of work into it so am not throwing that away.

**Comment by ColonelSandersLite** [comment]
Well, in BD, rifle start is traditional.  It's still the default.  Personally, I favor pistol starts since that was added as an option.  A shotgun may or may not be available early.  More importantly, enough ammo to really run it may or may not be available early.


I can take a look at the sprites after christmas if you like.

**Comment by BLOODWOLF333** [comment]
Yeah I suck at making sprites if I can find someone to do them at the same quality as what we already have then I can make it work no problem

**Comment by ColonelSandersLite** [comment]
You got steam blood?

Friend me.
80107883

**Comment by BLOODWOLF333** [comment]
I'm on both, your discord name isnt working when I try to FR
