### ISSUE TITLE
Weapon still disappears after kicking/tossing grenade in GZDoom

### ISSUE THREAD

**Issue by Anananel** [BLOODWOLF333/Brutal-Doom-Community-Expansion#376]
### Version
Brutal Doom Community Expansion v21.11.3 Stable

### Environment
PC (AMD Athlon II X2 240, ASUS EAH6570 Series)

### Port
GZDoom 4.6.0b (GLES fork)

### Description
Any weapon becomes invisible when kicking or tossing the grenade. It's coming back when firing. Bug only present in GZDoom, not in Zandronum (fixed long time ago)

**Comment by BLOODWOLF333** [comment]
I use GZDoom 4.5.0 that seems to be the last version that worked reliably with Brutal Doom and can't duplicate the issue.  The GZDoom devs have broken/changed things that conflict with Brutal Doom now and I will not break compatibility with Zandronum since that is all that I play online with the wife each night.  GZDoom is up to 4.7.1 maybe the latest version this is fixed or will have to roll back to around 4.5.0.  Dox's addon is optimized for GZD I know of as well.
