### ISSUE TITLE
help finding source of sound

### ISSUE THREAD

**Issue by Skrell** [BLOODWOLF333/Brutal-Doom-Community-Expansion#381]
Hi again, I've learned a lot since our last communication regarding DOOM modding; however, I'm totally stuck on 1 thing.  I'm trying to figure out how to add individual pickup sounds for each ammo type.  
I found in your original ammo.txt that you have ACTOR AmmoRocket : Ammo 2020 with a specified Inventory.Pickupsound "RCKCLIP".

However, no matter WHAT I change "RCKCLIP" to say, it ALWAYS plays the sound of the RCKCLIP file.   

So for example, I would expect if I changed it to say Inventory.Pickupsound "DSSAW3" that it would play the sound from the chainsaw when I pickup a rocket, but again, it STILL plays RCKCLIP sound.   What am I missing??

**Comment by BLOODWOLF333** [comment]
Are you making a patch or just modifying the brutalv21.x.x.pk3?  Only times I have run into an issue like that is because I didnt click save yet after making the changes before testing it or I didnt have the right copy loaded into the launcher (I use rocket launcher 2.0) when I went to test.  If your telling it a sound name that exists either as the name of the .wav or .ogg wtvr format file it is or whatever that sound is named in the SNDINFO lump then that should work.

**Comment by Skrell** [comment]
Unfortunately I'm definitely saving it correctly.   Would you do me a favor
and try the change I suggest and see what happens on your end?  I feel like
this is a bug with gzdoom possibly?

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/159576545-403a30ac-3104-434d-bc8a-bc7941cd5f94.png)
It works for me.  I pick up a rocket and it plays the chainsaw rip sound effect.  screenshot what you are doing.

**Comment by Skrell** [comment]
I don't know wtf is going on, but everything works now.... I don't think I changed anything other than to restart the megawad I was playing.... WEIRD.  Thank you for your time and patience!!
