### ISSUE TITLE
HUD Suggestion: Show both available ammo types for shotguns and Revolver simultaneously on Brutal Simple HUD.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#385]
### Description
It would be nice to see the shells/slugs (for shotguns) and magnum bullets/shells (for the Revolver) simultaneously displayed on at least the Brutal Simple HUD, likely with the current loaded ammo remaining displayed as-is, with the second, unloaded ammo-type displayed above it, with a smaller number font, likely the same one currently used for health/armor/grenades.

**Comment by BLOODWOLF333** [comment]
how?  It doesnt allow for 3 ammo types in SBARINFO.  ammotype1 is what is loaded in the gun and ammotype2 is the reserve pool of that ammotype or an ammotype that altfire will consume
https://zdoom.org/wiki/Classes:Weapon

**Comment by BLOODWOLF333** [comment]
I can't do this because the buckshot shotguns and the slug shotguns I had to make into two different weapons for each ammo type and same with the revolvers.  Since decorate doesnt allow a weapon to have 3 ammotypes and I dont want to overcomplicate the SBARINFO more than it already is.  I only have the pump and auto shotguns as slugs and the super as buckshot so, can do something like that to check how much of each type you have maybe.
