### ISSUE TITLE
Weapon number warning at startup

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#394]
### Version
v21.12.2 pre-release.

### Environment
Computer.

### Port
Zandronum 3.1 release.

### Description
I noticed this message is output into my console when I start the game with Zandronum 3.1 (no other mods).

`Warning: RifleSpawner and Pistol both have doomednum 5010.`

No idea if it's anything to worry about.

**Comment by BLOODWOLF333** [comment]
No its nothing to worry about.  Vanilla pistols are never placed on any map but they have an editor number and the Riflespawner replaces the pistol pickup so, I had to do this when I gave editor numbers to every weapon pickup so that I could place every specific weapon on the test map and the buzzsaw and unmaker in my BDCE version of EDay.
