### ISSUE TITLE
Some monsters that shooting on explosive barrels near them and can't deal damage

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#396]
### Version
v21.12.3 Hotfix

### Environment
PC

### Port
Zandronum 3.1 and LZDoom 3.88b

### Description
Some monsters like Arachnotron, Ancient Arachnotron and Mancubus shooting on explosive barrels near them and can't deal damage.

https://user-images.githubusercontent.com/76774186/188316460-dd110b04-42ab-4ba6-a277-8b719d4d446e.mp4

https://user-images.githubusercontent.com/76774186/188316461-a6c0ca8d-e5aa-42e9-80e6-68db08f08de0.mp4

https://user-images.githubusercontent.com/76774186/188316474-ba1551d6-5efe-430e-a49d-109150b8a822.mp4

Also, Hell Knight deal less damage shooting on explosive barrels near him.

https://user-images.githubusercontent.com/76774186/188316563-99980ab1-6944-4bcf-a10b-8938700e716e.mp4

**Comment by BLOODWOLF333** [comment]
thats because they have the +DONTHARMSPECIES flag which prevents them from killing themselves with their explosive/fire attacks or causing in-fighting with the same species.  This also ends up meaning they wont hurt themselves if they blow up a barrel next to them which yeah I dont really like that either.
But, removing this flag instead would mean that mancubus could end up suiciding and killing themselves with their fire (which do explosive damage) attacks and causing them to in-fight.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20220904_141454](https://user-images.githubusercontent.com/16950832/188329874-647f7436-b567-46ba-a831-8a12b5a5598f.png)
So I removed that +DONTHARMSPECIES flag from the monsters so now if they explode a barrel and damage another adjacent monster they will infight but if two mancubi are in fighting theyre not going to hurt each other so dont report that later as a bug.  And made sure that is vanilla Doom behavior as well after exploding a barrel they will in fight but cant hurt one another so that is all behaving correctly now.
