### ISSUE TITLE
No screen flash when picking up items

### ISSUE THREAD

**Issue by mrmatteastwood** [BLOODWOLF333/Brutal-Doom-Community-Expansion#399]
### Version
21.12.3HF

### Environment
Linux Mint 21

### Port
GZDoom

### Steps to Reproduce
1. Start a new game (e.g., DOOM 2) with brutalv21.12.3HF.pk3
2. Pick up any item

### Current Result
The screen doesn't flash when picking up an item.

### Expected Result
The screen should flash when picking up an item, as it does in original DOOM.

### Notes
Tried this without any other PWADS or mods. There's no interference that would trigger this issue. Also, when starting GZDoom without brutalv21.12.3HF.pk3, the screen flash is there. Tweaking the screen flash options in the GZDoom options menu doesn't make any difference.

**Comment by BLOODWOLF333** [comment]
I did this on purpose because it's annoying and headache-inducing to me.  When the wife and I play test each night on my online servers we go to the test map and load up on weapons and ammo before changing the map back to where we left off the night prior.  So running across all those tables with the screen blinking constantly gets annoying so I removed it.   I don't want it back.

**Comment by rautamiekka** [comment]
It could be a setting.

**Comment by mrmatteastwood** [comment]
Hey @BLOODWOLF333 I see what you mean. Let me say that of course, it's your mod and you're free to tweak it as you see fit. I enjoy it a whole lot and am impressed by how much work you guys are putting into it, it's awesome.

The missing screen flash is rather confusing to me and like @rautamiekka, I wonder if it wouldn't be too much trouble to add this as an option for those of us who prefer the original behaviour? I'd be truly grateful, but I understand if it's too much hassle.
