### ISSUE TITLE
Bullet casings - Halfway Through The Floor 💥🔫🚮

### ISSUE THREAD

**Issue by Danielkaas94** [BLOODWOLF333/Brutal-Doom-Community-Expansion#420]
### Version 🆓🆒
State if you are using the stable or which development snapshot version.
 • Stable - brutalv21.13.1.pk3

### Environment ♻
State whether this occurs on a computer or mobile device.
PC - Windows 10

### Port 🚪
State which port this occurs on whether GZdoom, Zandronum, or another Doom port.
 • I am using GZdoom 4.8.2

### Description 📜
Describe how you are able to reliably (hopefully) reproduce this issue and provide screenshots if able.
 • All bullet casings except shotgun shells are halfway through the floor
 • Using the "Adjust sprite clipping" seems to have no effect

![Screenshot_Doom_20230226_172824](https://user-images.githubusercontent.com/17402015/221423496-1a925399-8b6c-49a6-9eea-de997690f8cb.png)

**Comment by BLOODWOLF333** [comment]
Yep this is GZDoom fucking up things that were never broken.  Idk why GZDoom felt the need to mess with the sprites offsets, everything in GZDoom is like 2-4 units lower than how they are rendered in Zandronum.  GZDoom is shit and is why I dont care about the port they have changed/fixed things that were never broken and I refused to change this mod to adapt to their craziness.  In zandronum you will see all casings appear correctly and Zandronum multiplayer is the only port that I care about or can develop for since GZDoom wants to change stuff like this for no good reason.

**Comment by Danielkaas94** [comment]
Thanks for the clarifications and it is understandable! 
I will try it out on Zandronum then!

Take care!
❤🧡💛💚💙💜🤍
