### ISSUE TITLE
The Full Helmet HUD does not scale correctly.

### ISSUE THREAD

**Issue by ClevelandRock** [BLOODWOLF333/Brutal-Doom-Community-Expansion#423]
### Version
v21.13.2 Development

### Environment
Windows 10 PC

### Port
GZDoom version g4.11pre-149-gc3d99fa69

### Description
The Full Helmet HUD does not scale correctly. My resolution is 1920 by 1080. This is what it looks like:
![BD21132](https://user-images.githubusercontent.com/15882664/233506501-e412ba82-7ed1-4460-b59d-ad7f5aef439d.png)

This problem **only** exists with Brutal Doom Community Expansion. This is what it looks like with regular Brutal Doom v2.1:
![BD21](https://user-images.githubusercontent.com/15882664/233507055-1c49598b-867c-46e7-b30f-39d881349459.png)

**Comment by BLOODWOLF333** [comment]
Yeah I am aware.  A while ago a 4:3 box monitor user complained that this helmet HUD doesn't render correctly at his 800x600 resolution so I broke it into two parts like it is now which works for more resolutions than the vanilla version except for three or four of the highest resolutions available.  Doesn't seem to be any happy medium with this annoying HUD to make it work on every available aspect ratio so I will ask around and try to figure something out or just remove this because it is a headache to deal with.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20230420_231613](https://user-images.githubusercontent.com/16950832/233539759-b7b68cbb-7f3a-4aad-a8a3-dc22dd1e7097.png)
![HELMTOPa](https://user-images.githubusercontent.com/16950832/233539788-90857e5d-17e8-4134-a4bc-9b1135a96e37.png)
![HELMBOTMa](https://user-images.githubusercontent.com/16950832/233539799-a3e77eca-e911-40b4-9552-55fc1aabb979.png)
I think this should hopefully appease everyone
