### ISSUE TITLE
Can we get an "overview" of biggest changes you've made?

### ISSUE THREAD

**Issue by Skrell** [BLOODWOLF333/Brutal-Doom-Community-Expansion#434]
I've been following and playing with this project for a LONG time now and I've seen many changes evolve over time but realize now that I no longer have a sense of how different this MOD is from the original Bdv21.  
If you forget about the fixes to bugs and small errors you've made, do you think you could put together a list of the biggest GAMEPLAY changes you've made to date?  
For example, 2 big differences I've noticed is you changed the size of enemy sprites and the amount of damage they do.  I think it would be really helpful to know by what % these things have changed from the original Bdv21.

**Comment by BLOODWOLF333** [comment]
![image](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/16950832/b6ad942c-fb3c-45a2-914f-e0c8edc18f44)
Well I expect most people get this off of moddb.com, I guess I could add the description to the wiki on this as well.  And yeah I'm not wanting to make this radically different from v21 just "finished/fixed" is the main thing.

> If you forget about the fixes to bugs and small errors you've made, do you think you could put together a list of the biggest GAMEPLAY changes you've made to date?

What errors are still in this?

**Comment by Skrell** [comment]
So you're right the summary on mod DB was sort of what I was looking for but I was hoping to have more specifics about changes to things like accuracy or damage or sprite height.  I found that overtime the mod has become more difficult and I'd like to understand exactly what changed in case I wanted to tweak things back to make them easier

**Comment by BLOODWOLF333** [comment]
![image](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/16950832/7db584c8-27e8-4f51-9a76-ce1bdcb43383)
Man that is over 200+ files to document every change I have made.  I recommend getting notepad++ with the compare plugin and you can paste my v21.14.0 file and then the vanilla v21 file for each monster and weapon to quickly compare and see all the changes I made if you then want to go through and apply your own tweaks.

But as a quick summary:
I normalized all the damagefactors for the monsters regarding the damage they take from headshots, the SSG, fire, etc.  With the tough monsters (500+HP) taking 50% less damage from melee and fatality, 50% less from fire if the monsters can conjure fire like an Archvile or Bruiser.  And then boss monsters taking 50% less damage from all damagetypes If I remember correctly.

And then weapons I tweaked the accuracy and DPS values a little bit, nothing major I think.  Here are all my spreadsheets that I believe are up to date as of 21.14.0 I havent changed anything major since I last used these:
[DamageFactors.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/12060052/DamageFactors.zip)
[BrutalDoomFriendlyMarines.xlsx](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/12060053/BrutalDoomFriendlyMarines.xlsx)
[BrutalDoomMonsters20190930.xlsx](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/12060054/BrutalDoomMonsters20190930.xlsx)
[BrutalDoomWeapons.xlsx](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/12060055/BrutalDoomWeapons.xlsx)

**Comment by Skrell** [comment]
Thank you this is more what I was looking for!
