### ISSUE TITLE
Feature Request: Quick punch for berserk

### ISSUE THREAD

**Issue by Thelegendking** [BLOODWOLF333/Brutal-Doom-Community-Expansion#450]
### Description
Hi! I know that "Quick select fist" exist but there could a better alternative to this feature. "Quick Melee" pretty simple does a quick heavy punch but when player have the berserk it will do fatalities (without berserk its a normal weak punch), this will fit seamlessly with brutal doom combat mechanics it'll be fast and efficient cuz there no longer will be a need to change slots to do fatalities.

Thanks for fixing and making this mod better.

**Comment by BLOODWOLF333** [comment]
We already have the quick kick keybind which does the same but not fatalities.  I changed the quick select pistol to quick fists for the sake of being able to do fatalities quickly and because quick select pistol is useless.  I'm not sold on this idea or adding another keybind

**Comment by Thelegendking** [comment]
Hmm yeah I know quick select fist is there for that reason but quick heavy punch is even more useful when you're exploding hordes of demons but all of a sudden a demon came too close then the player uses "Quick Punch" on them to do fatality on them instantly without the need to switch slots after done doing fatality player would be back to the weapon the player was using its useful for sudden close encounters, isn't that what "Quick select fist" option is also trying to achieve but impacts the flow of combat?

Oh and also I meant this feature as a replacement for quick select fist not as another new keybind. Since both of them are trying to achieve same thing but quick punch being more faster and efficient.

**Comment by BLOODWOLF333** [comment]
![image](https://github.com/user-attachments/assets/429827cb-39e3-48db-bb19-76ecce1c8e8e)
Alright, the quick kick feature is accomplished by having inventory checks in every weapon file to check for a kicking token, and if present, will do the quick kick animation defined  in defaultweapon which they all inherit from.  That is 334 checks that I would have to change or duplicate to accomplish this.  I am not interested, its not a quick simple easy addition or change to make and it doesnt benefit my playstyle.  You are more than welcome to make your own addon or BD spinoff like others in the community do since there isnt a right or wrong way to play this game.

**Comment by Thelegendking** [comment]
Also Is it a known bug that shooting Imp at its leg with a shotgun does little to no damage?
