### ISSUE TITLE
Monster respawn is broken

### ISSUE THREAD

**Issue by ShadowMosesIsland** [BLOODWOLF333/Brutal-Doom-Community-Expansion#451]
### Version
_State if you are using the stable or which development snapshot version._

v21.15.0 Stable

### Environment
_State whether this occurs on a computer or mobile device._

Computer

### Port
_State which port this occurs on whether GZdoom, Zandronum, or another Doom port._

GZDoom and Zandronum.

### Description
_Describe how you are able to reliably (hopefully) reproduce this issue and provide screenshots if able._

1. Choose a difficulty with monster respawn, such as Nightmare.
OR
1. Enable monsters respawn in Gameplay options (GZDoom/Zandronum)
2. Kill every monster on the map.
3. Observe the monsters count and wait.

In my attempt of reproducing the issue on E1M1 Nightmare difficulty, I gave myself an autoshotgun with cheats, and killed every monster. Then I waited 5 minutes, and only 4 out of 29 respawned.

I'm pretty sure this is caused by the advanced gibbing system BD has, as monsters who were gibbed don't seem to respawn ever.

In an ideal scenario, monsters would be able to respawn, regardless of their corpse status, in a place where they were initially placed on the map.

**Comment by BLOODWOLF333** [comment]
Alright, problem is the monsters in their numerous death states (sometimes 20 or more for each monster) dont have an ending -1 frame when they spawn a gibbable corpse actor so they dont respawn.  This is intentional and vanilla behavior for lost souls and pain elementals but is going to take a lot of time to rewrite and correct in every monster but I will be working on it.
