### ISSUE TITLE
Level Enhancement System is partially-active, despite being manually disabled.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#8]
### Version
Dev Snapshot v0.0.1

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.85

### Description
Even if the Level Enhancement System is disabled in the options menu, some elements still manage to apply themselves. In Ultimate Doom, it's quite apparent in E1M8 and E2M5.

**Comment by BLOODWOLF333** [comment]
Like what specifically?  I never play with the LES off so, I dont remember what is and what is not part of it.

**Comment by Shockwave508** [comment]
Modified level textures (gore textures replacing the vines in the righthand nukage corridor on E2M5, or bloodstained walls almost everywhere in E2M6), additional environment objects (such as the chairs and red alarm lights in E1M1, or basically any breakable glass), increased enemy spawns in certain areas (such as additional Imps spawning in E3M3, or a Baron coming out of the exit teleporter in E3M1).

**Comment by BLOODWOLF333** [comment]
So that CVAR that is changed to a 0 or 1 depended on whether you turn the map enhancement option on/off only sets an actor's state to the Vanilla spawn state for weapons, ammo, and actual actors.  The texture replacements and all that are in scripts with no check for that CVAR.  So, I have no desire to create IF statements in 36+ scripts for this when I guess Mark stated he might take this out of BDv22.  So, I'm going to wait and see what he does in the next version.
